import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Appbar from '../components/AppBar'
import Autocomplete from '../components/Autocomplete'
import CustomCard from '../components/CustomCard'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Trailer Ahoy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://image.flaticon.com/icons/png/512/1112/1112155.png" />
      </Head>
      <Appbar/>      
      <main className={styles.main}>
        <h1 className={styles.title}>
          The best place to watch Trailers on the web!
        </h1>

        <p className={styles.description}>
        <Autocomplete/>
        </p>

        <div className={styles.grid}>
        
        </div>
      </main>
  

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{'Ahoy! inc'}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
